"""estrutura inicial sqlalchemy v2

Revision ID: 96f5e02db838
Revises: 
Create Date: 2026-09-04 15:14:59.399186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96f5e02db838'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor_aquisicao', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_aquisicao', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('imovel', 'veiculo', 'joia', 'eletronico', 'colecionavel', 'outro')", name='ck_bens_tipo'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_bens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bem_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor >= 0', name='ck_historico_bens_valor'),
    sa.ForeignKeyConstraint(['bem_id'], ['bens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bem_id', 'data_referencia', name='uq_historico_bens_bem_data')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column(
              'criado_em',
              existing_type=postgresql.TIMESTAMP(),
              type_=sa.DateTime(timezone=True),
              nullable=False,
              existing_server_default=sa.text('CURRENT_TIMESTAMP'),
              postgresql_using="criado_em AT TIME ZONE 'UTC'"
              )
        batch_op.create_unique_constraint('uq_categorias_id_usuario', ['id', 'usuario_id'])
        batch_op.drop_constraint(batch_op.f('categorias_tipo_check'), type_='check')
        batch_op.create_check_constraint('ck_categorias_tipo', "tipo IN ('receita', 'gasto', 'investimento', 'resgate')")

    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('valor',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.create_index('ix_lancamentos_usuario_data', ['usuario_id', 'data'], unique=False)
        batch_op.drop_constraint(batch_op.f('lancamentos_categoria_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('lancamentos_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_lancamentos_categoria_usuario', 'categorias', ['categoria_id', 'usuario_id'], ['id', 'usuario_id'])
        batch_op.create_check_constraint('ck_lancamentos_valor_positivo', 'valor > 0')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column(
              'criado_em',
              existing_type=postgresql.TIMESTAMP(),
              type_=sa.DateTime(timezone=True),
              nullable=False,
              existing_server_default=sa.text('CURRENT_TIMESTAMP'),
              postgresql_using="criado_em AT TIME ZONE 'UTC'"
              )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('ativo')

    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.drop_constraint('ck_lancamentos_valor_positivo', type_='check')
        batch_op.drop_constraint('fk_lancamentos_categoria_usuario', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lancamentos_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('lancamentos_categoria_id_fkey'), 'categorias', ['categoria_id'], ['id'])
        batch_op.drop_index('ix_lancamentos_usuario_data')
        batch_op.alter_column('valor',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('criado_em')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint('ck_categorias_tipo', type_='check')
        batch_op.create_check_constraint(batch_op.f('categorias_tipo_check'), "tipo::text = ANY (ARRAY['receita'::character varying::text, 'gasto'::character varying::text])")
        batch_op.drop_constraint('uq_categorias_id_usuario', type_='unique')
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('ativo')

    op.drop_table('historico_bens')
    op.drop_table('bens')
    # ### end Alembic commands ###
